name: Build and Developmental Release

on:
  push:
    branches: 
      - '**'  # Trigger on any branch push
  workflow_dispatch:

jobs:
  build:
    name: Build x64-Release
    runs-on: windows-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: geode-sdk/build-geode-mod@main
        id: build

      - name: Compress Build Output
        run: |
          mkdir out
          cp -r bin/resources out/resources
          cp README.md out/about.md
          cp bin/changelog.md out/
          cp bin/logo.png out/
          cp mod.json out/
          cp build/*.dll out/
          cd out
          7z a -tzip rainixgd.geome3dash.geode -mx9 *
         
      # Upload the compressed file
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rainixgd.geome3dash.geode
          path: out/rainixgd.geome3dash.geode

  release:
    name: Create Developmental Release
    needs: build
    runs-on: ubuntu-latest
    if: false

    steps:
      # Download the compressed build artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: rainixgd.geome3dash.geode
          path: .

      # Create GitHub Release
      - name: Update Development Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: develop
          name: 'Developmental Build'
          body: |
            Geome3dash development release for commit ${{ github.sha }}.
          files: |
            ./rainixgd.geome3dash.geode
