name: Build and Developmental Release

on:
  push:
    branches: 
      - '*'  # Trigger on any branch push

name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: true
          target: ${{ matrix.config.target }}

jobs:
  build:
    name: Build x64-Release
    runs-on: windows-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: geode-sdk/build-geode-mod@main
        id: build

      - name: Compress Build Output
        run: |
          mkdir out
          cp -r bin/resources out/resources
          cp README.md out/about.md
          cp bin/changelog.md out/
          cp bin/logo.png out/
          cp mod.json out/
          cp build/*.dll out/
          7z a -tzip "out/rainixgd.geome3dash.geode" -mx9 "out/*"
         
      # Upload the compressed file
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rainixgd.geome3dash.geode
          path: out/rainixgd.geome3dash.geode

  release:
    name: Create Developmental Release
    needs: build
    runs-on: ubuntu-latest
    if: false

    steps:
      # Download the compressed build artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: rainixgd.geome3dash.geode
          path: .

      # Create GitHub Release
      - name: Update Development Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: develop
          name: 'Developmental Build'
          body: |
            Geome3dash development release for commit ${{ github.sha }}.
          files: |
            ./rainixgd.geome3dash.geode
